ALTER TABLE public.licencias 
ADD COLUMN IF NOT EXISTS gratis_activa BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS basica_activa BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS pro_activa BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS premium_activa BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS exclusiva_activa BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS soundkits_activa BOOLEAN DEFAULT true;
