
export const COUNTRIES = [
    "México 🇲🇽",
    "Estados Unidos 🇺🇸",
    "Argentina 🇦🇷",
    "Colombia 🇨🇴",
    "España 🇪🇸",
    "Chile 🇨🇱",
    "Perú 🇵🇪",
    "Venezuela 🇻🇪",
    "Ecuador 🇪🇨",
    "República Dominicana 🇩🇴",
    "Puerto Rico 🇵🇷",
    "Guatemala 🇬🇹",
    "Bolivia 🇧🇴",
    "Cuba 🇨🇺",
    "Honduras 🇭🇳",
    "Paraguay 🇵🇾",
    "El Salvador 🇸🇻",
    "Nicaragua 🇳🇮",
    "Costa Rica 🇨🇷",
    "Panamá 🇵🇦",
    "Uruguay 🇺🇾",
    "Brasil 🇧🇷",
    "Canadá 🇨🇦",
    "Reino Unido 🇬🇧",
    "Francia 🇫🇷",
    "Italia 🇮🇹",
    "Alemania 🇩🇪",
    "Otro 🌍"
];

export const GENRES = [
    "Corridos Tumbados 🇲🇽",
    "Sierreño 🌵",
    "Banda / Norteño 🎺",
    "Mariachi Moderno 🎻",
    "Reggaetón 🍑",
    "Reggaetón Mexa 🇲🇽",
    "Dembow 🇩🇴",
    "Dancehall 🇯🇲",
    "Trap Latino 🔥",
    "R&B 🕯️",
    "Baile Funk 🇧🇷",
    "Afrobeats 🌍",
    "Boom Bap 🥁",
    "Drill 🔪",
    "Lo-Fi ☕",
    "Gangsta Rap 🔫",
    "House 🏠",
    "Hyperpop 🍭",
    "Techno ⛓️",
    "Phonk 🚗",
    "Pop / Indie 🎸",
    "Piano 🎹",
    "Trap 💎",
    "Hip Hop 🎤",
    "Rock 🤘",
    "Alternativo 🌀"
];

export const SUBGENRES: Record<string, string[]> = {
    "Corridos Tumbados 🇲🇽": ["Bélicos 🦅", "Tumbados Románticos ❤️", "Corridos de Calle 🚬", "Trap Corridos 💎", "Sierreño Tumbado 🌵"],
    "Sierreño 🌵": ["Campirano 🤠", "Sierreño Tumbado 🎸", "Romántico 🌹", "Clásico 🎻"],
    "Banda / Norteño 🎺": ["Quebradita 💃", "Zapateado 🕺", "Huapango 🎻", "Norteño Sax 🎷", "Banda Sinaloense 🎺"],
    "Mariachi Moderno 🎻": ["Regional Pop 💎", "Mariacheño 🤠", "Mariachi Trap 🔥", "Clásico 🎻"],
    "Reggaetón 🍑": ["Old School 👴", "Perreo Pesado 🔥", "Romantiqueo ❤️", "Neoperreo 🌈", "Reggaetón Flow 🌊", "Mambo 💃"],
    "Reggaetón Mexa 🇲🇽": ["Mexa Bass 🇲🇽", "Perreo Chilango 🚬", "Flow Bajío 🌵", "Reggaetón Bélico 🦅"],
    "Dembow 🇩🇴": ["Dembow Dominicano 🇩🇴", "Bajo Mundo 🇩🇴", "Dembow Calle 🚬", "Afro Dembow 🌍"],
    "Dancehall 🇯🇲": ["Ragga 🔊", "Rockers 🎸", "Bashment 🔥", "Lovers Rock ❤️"],
    "Trap Latino 🔥": ["Melodic Trap 🌊", "Dark Trap 🌑", "Pluggnb 🔌", "Latin Drill 🔪", "Trap Soul 🕯️", "Ethereal Trap ✨"],
    "R&B 🕯️": ["Soul Moderno ✨", "R&B Alternativo 🌫️", "Neo-Soul 🧘", "Contemporary R&B 🕯️", "PBR&B 🌊"],
    "Baile Funk 🇧🇷": ["Funk Carioca 🇧🇷", "Brazilian Bass 🇧🇷", "Funk Ostentação 💰", "Funk Proibidão 🚫"],
    "Afrobeats 🌍": ["Afro-Fusion 🌍", "Amapiano 🇿🇦", "Afro-Swing 🌊", "Afro-Jazz 🎷"],
    "Boom Bap 🥁": ["Lo-Fi Hip Hop ☕", "Jazz Hop 🎷", "Hardcore Hip Hop 🥁", "Conscious Rap 🧘"],
    "Drill 🔪": ["UK Drill 🇬🇧", "NY Drill 🗽", "Latin Drill 🔥", "Sample Drill 📀"],
    "Lo-Fi ☕": ["Chillhop 🌊", "Study Beats 📚", "Jazz-Fi 🎷", "Ambient Lo-Fi 🧘"],
    "Gangsta Rap 🔫": ["G-Funk 🌴", "West Coast 🌴", "East Coast 🗽", "Dirty South 🦅"],
    "House 🏠": ["Tech House 🔊", "Deep House 🌊", "Afro House 🌍", "Melodic House ✨", "Slap House 🔨"],
    "Hyperpop 🍭": ["Glitchcore 👾", "Bubblegum Bass 🍬", "Cyberpop 💻", "Digicore 💿"],
    "Techno ⛓️": ["Hard Techno 🔨", "Acid Techno 🧪", "Industrial Techno ⚙️", "Peak Time Techno ⚡"],
    "Phonk 🚗": ["Drift Phonk 💨", "Brazilian Phonk 🇧🇷", "Rare Phonk 💎", "Vamp Phonk 🧛"],
    "Pop / Indie 🎸": ["Dream Pop ☁️", "Synth Pop 🎹", "Indie Rock 🎸", "Bedroom Pop 🛏️", "Alt-Pop 🌀"],
    "Piano 🎹": ["Piano Melódico 🎹", "Piano Instrumental 🎹", "Piano Trap 🔥", "Piano Sad 💔"],
    "Trap 💎": ["EDM Trap 🔊", "Trap Soul 🕯️", "Hard Trap 🔨", "Chill Trap 🌊"],
    "Hip Hop 🎤": ["Old School 🎤", "Underground 🎤", "Cloud Rap ☁️", "Emo Rap 💔"],
    "Rock 🤘": ["Metal 🤘", "Grunge 🎸", "Punk ⚡", "Indie Rock 🎸", "Psychedelic Rock 🍄"],
    "Alternativo 🌀": ["Experimental 🧪", "Avant-Garde 🎨", "Art Pop 🎨", "Shoegaze 🌫️"]
};

export const MOODS = [
    // Energía Positiva
    { label: "Feliz", emoji: "😊", color: "text-amber-500 bg-amber-50 border-amber-100" },
    { label: "Entusiasmado", emoji: "🤩", color: "text-yellow-500 bg-yellow-50 border-yellow-100" },
    { label: "Inspirador", emoji: "✨", color: "text-blue-400 bg-blue-50 border-blue-100" },
    { label: "Romántico", emoji: "❤️", color: "text-red-500 bg-red-50 border-red-100" },
    { label: "De Fiesta", emoji: "🥳", color: "text-pink-500 bg-pink-50 border-pink-100" },
    { label: "Triunfante", emoji: "🏆", color: "text-yellow-600 bg-yellow-50 border-yellow-100" },
    { label: "Motivado", emoji: "💪", color: "text-emerald-600 bg-emerald-50 border-emerald-100" },
    // Actitud y "Flex"
    { label: "Agresivo", emoji: "🔥", color: "text-red-600 bg-red-50 border-red-100" },
    { label: "Malandro", emoji: "👺", color: "text-rose-600 bg-rose-50 border-rose-100" },
    { label: "Poderoso", emoji: "⚡", color: "text-amber-600 bg-amber-50 border-amber-100" },
    { label: "Elegante", emoji: "👔", color: "text-slate-700 bg-slate-50 border-slate-100" },
    { label: "Desafiante", emoji: "🤨", color: "text-orange-600 bg-orange-50 border-orange-100" },
    { label: "Crudo", emoji: "🦴", color: "text-stone-600 bg-stone-50 border-stone-100" },
    // Relajación y Melancolía
    { label: "Triste / Depresivo", emoji: "💔", color: "text-indigo-600 bg-indigo-50 border-indigo-100" },
    { label: "Relajado / Chill", emoji: "🌊", color: "text-cyan-600 bg-cyan-50 border-cyan-100" },
    { label: "Nostálgico", emoji: "🎞️", color: "text-orange-500 bg-orange-50 border-orange-100" },
    { label: "Psicodélico", emoji: "🍄", color: "text-purple-600 bg-purple-50 border-purple-100" },
    { label: "Oscuro / Tenebroso", emoji: "🌑", color: "text-slate-800 bg-slate-100 border-slate-200" },
    { label: "Sensual", emoji: "🔞", color: "text-rose-500 bg-rose-50 border-rose-100" },
    { label: "Misterioso", emoji: "🕵️", color: "text-indigo-800 bg-indigo-50 border-indigo-100" },
    // Vibras "Tumbadas"
    { label: "Alucín", emoji: "🕶️", color: "text-slate-900 bg-slate-100 border-slate-200" },
    { label: "Bélico", emoji: "🦅", color: "text-green-800 bg-green-50 border-green-100" },
    { label: "Dolido", emoji: "🥃", color: "text-stone-800 bg-stone-50 border-stone-100" }
];
